# Generated by Django 2.2.4 on 2019-08-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extendeduser',
        ),
    ]
